### ISSUE TITLE
The search request was unable to connect to the Search Service

### ISSUE THREAD

**Issue by Chunlong101** [Chunlong101/PowershellScripts#1]
https://support.microsoft.com/en-sg/help/2888383/sharepoint-search-queries-fail-with-the-search-request-was-unable-to-c

Fetching app info failed: Microsoft.Office.Server.Search.Query.SearchServiceNotFoundException: The search request was unable to connect to the Search Service.    
 at Microsoft.Office.Server.Search.Administration.SearchServiceApplicationProxy.GetProxy(SPServiceContext ServiceContext)    
 at Microsoft.Office.Server.Search.WebControls.SearchCommon.GetSearchCenterUrl()

The following exception message may be displayed in the ULS log: 

CoreResultsWebPart::OnInit: Exception initializing: Microsoft.Office.Server.Search.Query.SearchServiceNotFoundException: The search request was unable to connect to the Search Service.
at Microsoft.Office.Server.Search.Administration.SearchServiceApplicationProxy.GetProxy(SPServiceContext ServiceContext) 
at Microsoft.Office.Server.Search.WebControls.CoreResultsWebPart.SetPropertiesOnQueryReader() 
at Microsoft.Office.Server.Search.WebControls.CoreResultsWebPart.OnInit(EventArgs e)

Cause
The Search Service Application Proxy does not exist in the farm. The Search Service Application Proxy is responsible for the communication between the WFE's search web part and the Search Service Application on the application server. 
Resolution
If the Search Service Application does not have a proxy then create a new proxy using PowerShell cmdlets:

$searchServiceApp = Get-SPEnterpriseSearchServiceApplication

New-SPEnterpriseSearchServiceApplicationProxy -SearchApplication $searchServiceApp

**Comment by Chunlong101** [comment]
Need a application proxy for the SSA.
